# Generated by Django 2.0.4 on 2018-04-19 02:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Game day')),
            ],
            options={
                'verbose_name': 'Belote Game',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Location',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('nickname', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Player',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=2)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='play.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='play.Player')),
            ],
            options={
                'verbose_name': 'Belote Team',
                'ordering': ['game'],
            },
        ),
        migrations.CreateModel(
            name='Trick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_ns', models.IntegerField(default=0)),
                ('score_ew', models.IntegerField(default=0)),
                ('belote_ns', models.IntegerField(default=0)),
                ('belote_ew', models.IntegerField(default=0)),
                ('round_taken', models.IntegerField()),
                ('card', models.CharField(max_length=10)),
                ('suit', models.CharField(max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='play.Game')),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='play.Player')),
            ],
            options={
                'verbose_name': 'Belote Trick',
                'ordering': ['score_ns'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='play.Location'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(through='play.Team', to='play.Player'),
        ),
    ]
