# Generated by Django 2.0.4 on 2018-04-19 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trick',
            old_name='score_ew',
            new_name='score_e',
        ),
    ]
