# Generated by Django 2.0.4 on 2018-04-19 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_auto_20180419_0214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trick',
            old_name='score_e',
            new_name='score_ew',
        ),
    ]
