# Generated by Django 2.0.4 on 2018-04-21 23:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_auto_20180419_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Game day'),
        ),
    ]
