# Generated by Django 2.0.4 on 2018-04-22 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0006_auto_20180422_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trick',
            options={'ordering': ['number'], 'verbose_name': 'Belote Trick'},
        ),
        migrations.AddField(
            model_name='trick',
            name='number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='trick',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.Game'),
        ),
    ]
